hostname: '0.0.0.0'
port: 30027
serverApi: 'https://api-poolon.noussol.fr'
JWT_SECRET: 'POOLONSTREAMEEEEEEERpopoposjudddjiiir!!de98*ifjdsuhfvdijsn19788854zfezfççé--*hjnfffhf!==uuuu'
JWT_SECRET_USER: 'POOLONSTREAMEEEEEEERUUUUUSSSSEEEERRpopoposjudddjiiir!!de98*ifjdsuhfvdijsn19788854zfezfççé--*hjnfffhf!==uuuu'
logLevel: 'debug'
videoPath: '/home/site/wwwroot/videos'
thumbnailsPath: '/home/site/wwwroot/thumbnails'
devicesLogsPath: '/home/site/wwwroot/devicesLogs'
templateMail:
  resetAdminPassword: '/home/site/wwwroot/mailTemplates/resetAdminPassword.html'
  mailCreateAdmin: '/home/site/wwwroot/mailTemplates/createdAdmin.html'
  deleteAdmin: '/home/site/wwwroot/mailTemplates/deleteAdmin.html'
  mailCreateUser: '/home/site/wwwroot/mailTemplates/createUser.html'
  deleteUser: '/home/site/wwwroot/mailTemplates/deleteUser.html'
  resetUserPassword: '/home/site/wwwroot/mailTemplates/resetUserPassword.html'

mail:
  server: 'noussol.fr'
  port: '465'
  users:
    contact:
      username: poolon
      password: 'Poolon13600**'
database:
  host: localhost
  port: 3306
  user: 'eljzrhleav'
  password: 'FwUgTuKu$Bni4j9w'
  database: 'api-poolon-v3-database'